package net.luversof.bookkeeping.constant;

public enum BookkeepingErrorCode {
	NOT_EXIST_BOOKKEEPING,
	NOT_EXIST_ASSET,
	NOT_EXIST_ASSETGROUP,
	NOT_EXIST_ENTRY,
	NOT_EXIST_ENTRYGROUP,
	NOT_EXIST_USER_ID,
	NOT_EXIST_BOOKKEEPING_ID,

	NOT_OWNER_BOOKKEEPING,
	NOT_OWNER_ASSET,
	NOT_OWNER_ASSETGROUP,
	NOT_OWNER_ENTRY,
	NOT_OWNER_ENTRYGROUP,
	
	NOT_SUPPORT_CHRONOUNIT,
	
	NOT_EXIST_INCOME_ASSET,
	NOT_EXIST_EXPENSE_ASSET,
	NOT_OWNER_INCOME_ASSET,
	NOT_OWNER_EXPENSE_ASSET,
	
	DISABLED_CHANGE_ASSET_GROUP
	;
}
